/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DailyQuestion: typeof import('./src/components/DailyQuestion.vue')['default']
    FrontendModules: typeof import('./src/components/FrontendModules.vue')['default']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    QuestionDetail: typeof import('./src/components/QuestionDetail.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
  }
}
