/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CosmosHeadbar: typeof import('./src/components/CosmosHeadbar.vue')['default']
    DailyQuestion: typeof import('./src/components/DailyQuestion.vue')['default']
    FrontendModules: typeof import('./src/components/FrontendModules.vue')['default']
    KnowledgeCosmos: typeof import('./src/components/KnowledgeCosmos.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    QuestionDetail: typeof import('./src/components/QuestionDetail.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
  }
}
